"""initial_schema

Revision ID: c90920aea219
Revises: 
Create Date: 2026-10-08 20:52:30.682402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c90920aea219'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_name'), 'trades', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('WORKER', 'CONTRACTOR', 'SUPERVISOR', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='userstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('contractors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('contact_person', sa.String(length=120), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contractors_id'), 'contractors', ['id'], unique=False)
    op.create_index(op.f('ix_contractors_user_id'), 'contractors', ['user_id'], unique=True)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id', 'name', name='uq_trade_skill_name')
    )
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=False)
    op.create_index(op.f('ix_skills_trade_id'), 'skills', ['trade_id'], unique=False)
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferred_language', sa.String(length=20), nullable=False),
    sa.Column('home_region', sa.String(length=120), nullable=True),
    sa.Column('current_work_region', sa.String(length=120), nullable=True),
    sa.Column('expected_daily_wage', sa.Float(), nullable=True),
    sa.Column('availability_status', sa.Enum('AVAILABLE', 'UNAVAILABLE', 'WORKING', 'ASSIGNED', 'ON_LEAVE', 'UNKNOWN', name='workeravailability'), nullable=False),
    sa.Column('profile_status', sa.String(length=50), nullable=False),
    sa.Column('verification_status', sa.Enum('UNVERIFIED', 'BASIC_VERIFIED', 'FULLY_VERIFIED', name='workerverificationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workers_availability_status'), 'workers', ['availability_status'], unique=False)
    op.create_index(op.f('ix_workers_id'), 'workers', ['id'], unique=False)
    op.create_index(op.f('ix_workers_user_id'), 'workers', ['user_id'], unique=True)
    op.create_table('preferred_workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contractor_id', 'worker_id', name='uq_contractor_preferred_worker')
    )
    op.create_index(op.f('ix_preferred_workers_contractor_id'), 'preferred_workers', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_preferred_workers_id'), 'preferred_workers', ['id'], unique=False)
    op.create_index(op.f('ix_preferred_workers_worker_id'), 'preferred_workers', ['worker_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_status', sa.Enum('PLANNED', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='projectstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('expected_end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_contractor_id'), 'projects', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_project_status'), 'projects', ['project_status'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_contractor_id'), 'teams', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_table('worker_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('skill_level', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.Enum('SELF_DECLARED', 'CONTRACTOR_VERIFIED', 'SUPERVISOR_VERIFIED', 'WORK_VERIFIED', 'CERTIFIED', name='verificationstatus'), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('evidence_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id', 'skill_id', name='uq_worker_skill')
    )
    op.create_index(op.f('ix_worker_skills_id'), 'worker_skills', ['id'], unique=False)
    op.create_index(op.f('ix_worker_skills_skill_id'), 'worker_skills', ['skill_id'], unique=False)
    op.create_index(op.f('ix_worker_skills_worker_id'), 'worker_skills', ['worker_id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    op.create_index(op.f('ix_sites_project_id'), 'sites', ['project_id'], unique=False)
    op.create_index(op.f('ix_sites_region'), 'sites', ['region'], unique=False)
    op.create_index(op.f('ix_sites_supervisor_id'), 'sites', ['supervisor_id'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('minimum_skill_level', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_members_id'), 'team_members', ['id'], unique=False)
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_table('labour_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('required_start_date', sa.Date(), nullable=False),
    sa.Column('required_end_date', sa.Date(), nullable=False),
    sa.Column('work_schedule', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'FULFILLED', 'CANCELLED', name='requirementstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('required_end_date >= required_start_date', name='chk_req_dates'),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labour_requirements_contractor_id'), 'labour_requirements', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_labour_requirements_id'), 'labour_requirements', ['id'], unique=False)
    op.create_index(op.f('ix_labour_requirements_project_id'), 'labour_requirements', ['project_id'], unique=False)
    op.create_index(op.f('ix_labour_requirements_site_id'), 'labour_requirements', ['site_id'], unique=False)
    op.create_index(op.f('ix_labour_requirements_status'), 'labour_requirements', ['status'], unique=False)
    op.create_table('labour_requirement_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('minimum_skill_level', sa.Integer(), nullable=False),
    sa.Column('quantity_required', sa.Integer(), nullable=False),
    sa.Column('wage_rate', sa.Float(), nullable=False),
    sa.Column('wage_period', sa.Enum('DAILY', 'HOURLY', 'MONTHLY', name='wageperiod'), nullable=False),
    sa.Column('duration', sa.String(length=80), nullable=True),
    sa.Column('schedule', sa.String(length=80), nullable=True),
    sa.Column('filled_quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PARTIALLY_FILLED', 'FILLED', 'CANCELLED', name='itemstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('filled_quantity >= 0', name='chk_item_filled_non_negative'),
    sa.CheckConstraint('quantity_required > 0', name='chk_item_qty_positive'),
    sa.CheckConstraint('wage_rate >= 0', name='chk_item_wage_non_negative'),
    sa.ForeignKeyConstraint(['requirement_id'], ['labour_requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labour_requirement_items_id'), 'labour_requirement_items', ['id'], unique=False)
    op.create_index(op.f('ix_labour_requirement_items_requirement_id'), 'labour_requirement_items', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_labour_requirement_items_skill_id'), 'labour_requirement_items', ['skill_id'], unique=False)
    op.create_index(op.f('ix_labour_requirement_items_trade_id'), 'labour_requirement_items', ['trade_id'], unique=False)
    op.create_table('job_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_item_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('offered_wage', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'CANCELLED', name='offerstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requirement_item_id'], ['labour_requirement_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_offers_id'), 'job_offers', ['id'], unique=False)
    op.create_index(op.f('ix_job_offers_requirement_item_id'), 'job_offers', ['requirement_item_id'], unique=False)
    op.create_index(op.f('ix_job_offers_status'), 'job_offers', ['status'], unique=False)
    op.create_index(op.f('ix_job_offers_worker_id'), 'job_offers', ['worker_id'], unique=False)
    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_item_id', sa.Integer(), nullable=True),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('role_title', sa.String(length=100), nullable=False),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'REVISED', 'COMPLETED', 'TERMINATED', name='workorderstatus'), nullable=False),
    sa.Column('acceptance_timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_item_id'], ['labour_requirement_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_orders_contractor_id'), 'work_orders', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_work_orders_id'), 'work_orders', ['id'], unique=False)
    op.create_index(op.f('ix_work_orders_project_id'), 'work_orders', ['project_id'], unique=False)
    op.create_index(op.f('ix_work_orders_requirement_item_id'), 'work_orders', ['requirement_item_id'], unique=False)
    op.create_index(op.f('ix_work_orders_site_id'), 'work_orders', ['site_id'], unique=False)
    op.create_index(op.f('ix_work_orders_status'), 'work_orders', ['status'], unique=False)
    op.create_index(op.f('ix_work_orders_worker_id'), 'work_orders', ['worker_id'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ASSIGNED', 'ACTIVE', 'COMPLETED', 'CANCELLED', 'REPLACED', name='assignmentstatus'), nullable=False),
    sa.Column('replacement_reason', sa.Text(), nullable=True),
    sa.Column('replaced_by_assignment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replaced_by_assignment_id'], ['assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_id'), 'assignments', ['id'], unique=False)
    op.create_index(op.f('ix_assignments_project_id'), 'assignments', ['project_id'], unique=False)
    op.create_index(op.f('ix_assignments_site_id'), 'assignments', ['site_id'], unique=False)
    op.create_index(op.f('ix_assignments_status'), 'assignments', ['status'], unique=False)
    op.create_index(op.f('ix_assignments_work_order_id'), 'assignments', ['work_order_id'], unique=False)
    op.create_index(op.f('ix_assignments_worker_id'), 'assignments', ['worker_id'], unique=False)
    op.create_table('communication_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('communication_type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.Enum('APP', 'SMS', 'IVR', 'VOICE', 'OTHER', name='commchannel'), nullable=False),
    sa.Column('status', sa.Enum('CALLING', 'ANSWERED', 'ACCEPTED', 'REJECTED', 'NO_RESPONSE', 'INVALID_NUMBER', 'FAILED', name='commstatus'), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('provider_reference', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['offer_id'], ['job_offers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_logs_contractor_id'), 'communication_logs', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_communication_logs_created_at'), 'communication_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_communication_logs_id'), 'communication_logs', ['id'], unique=False)
    op.create_index(op.f('ix_communication_logs_offer_id'), 'communication_logs', ['offer_id'], unique=False)
    op.create_index(op.f('ix_communication_logs_status'), 'communication_logs', ['status'], unique=False)
    op.create_index(op.f('ix_communication_logs_worker_id'), 'communication_logs', ['worker_id'], unique=False)
    op.create_table('work_order_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('agreed_wage_rate', sa.Float(), nullable=False),
    sa.Column('wage_period', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('working_schedule', sa.String(length=100), nullable=False),
    sa.Column('terms_text', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('worker_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_order_id', 'version_number', name='uq_work_order_version')
    )
    op.create_index(op.f('ix_work_order_versions_id'), 'work_order_versions', ['id'], unique=False)
    op.create_index(op.f('ix_work_order_versions_work_order_id'), 'work_order_versions', ['work_order_id'], unique=False)
    op.create_table('worker_contact_releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=False),
    sa.Column('release_reason', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_id'], ['job_offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_contact_releases_contractor_id'), 'worker_contact_releases', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_worker_contact_releases_id'), 'worker_contact_releases', ['id'], unique=False)
    op.create_index(op.f('ix_worker_contact_releases_offer_id'), 'worker_contact_releases', ['offer_id'], unique=False)
    op.create_index(op.f('ix_worker_contact_releases_worker_id'), 'worker_contact_releases', ['worker_id'], unique=False)
    op.create_table('attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(), nullable=True),
    sa.Column('check_out_time', sa.DateTime(), nullable=True),
    sa.Column('worker_confirmed', sa.Boolean(), nullable=False),
    sa.Column('supervisor_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('attendance_status', sa.Enum('PRESENT', 'ABSENT', 'PENDING_CONFIRMATION', 'DISPUTED', 'CANCELLED', name='attendancestatus'), nullable=False),
    sa.Column('confirmation_method', sa.Enum('APP', 'IVR', 'SMS', 'SUPERVISOR', 'MANUAL', 'SITE_DEVICE', 'QR', name='confirmationmethod'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'date', name='uq_assignment_date_attendance')
    )
    op.create_index(op.f('ix_attendances_assignment_id'), 'attendances', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_attendances_attendance_status'), 'attendances', ['attendance_status'], unique=False)
    op.create_index(op.f('ix_attendances_date'), 'attendances', ['date'], unique=False)
    op.create_index(op.f('ix_attendances_id'), 'attendances', ['id'], unique=False)
    op.create_index(op.f('ix_attendances_worker_id'), 'attendances', ['worker_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('incident_type', sa.Enum('INJURY', 'NEAR_MISS', 'SAFETY_VIOLATION', 'EQUIPMENT_INCIDENT', 'OTHER', name='incidenttype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('witnesses', sa.Text(), nullable=True),
    sa.Column('worker_statement', sa.Text(), nullable=True),
    sa.Column('supervisor_statement', sa.Text(), nullable=True),
    sa.Column('evidence_reference', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('REPORTED', 'UNDER_INVESTIGATION', 'RESOLVED', 'CLOSED', name='incidentstatus'), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_assignment_id'), 'incidents', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_incidents_contractor_id'), 'incidents', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_index(op.f('ix_incidents_incident_type'), 'incidents', ['incident_type'], unique=False)
    op.create_index(op.f('ix_incidents_project_id'), 'incidents', ['project_id'], unique=False)
    op.create_index(op.f('ix_incidents_site_id'), 'incidents', ['site_id'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index(op.f('ix_incidents_worker_id'), 'incidents', ['worker_id'], unique=False)
    op.create_table('sos_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('location_available', sa.Boolean(), nullable=False),
    sa.Column('location_reference', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('TRIGGERED', 'ACKNOWLEDGED', 'ESCALATED', 'RESOLVED', 'FALSE_ALARM', name='sosstatus'), nullable=False),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sos_alerts_assignment_id'), 'sos_alerts', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_sos_alerts_id'), 'sos_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_sos_alerts_project_id'), 'sos_alerts', ['project_id'], unique=False)
    op.create_index(op.f('ix_sos_alerts_site_id'), 'sos_alerts', ['site_id'], unique=False)
    op.create_index(op.f('ix_sos_alerts_status'), 'sos_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_sos_alerts_worker_id'), 'sos_alerts', ['worker_id'], unique=False)
    op.create_table('voice_evidences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('consent_status', sa.String(length=50), nullable=False),
    sa.Column('storage_path', sa.String(length=255), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('extracted_terms', sa.JSON(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('retention_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_evidences_assignment_id'), 'voice_evidences', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_voice_evidences_contractor_id'), 'voice_evidences', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_voice_evidences_id'), 'voice_evidences', ['id'], unique=False)
    op.create_index(op.f('ix_voice_evidences_worker_id'), 'voice_evidences', ['worker_id'], unique=False)
    op.create_table('payment_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('attendance_id', sa.Integer(), nullable=True),
    sa.Column('agreed_amount', sa.Float(), nullable=False),
    sa.Column('amount_due', sa.Float(), nullable=False),
    sa.Column('amount_reported_paid', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.Enum('UPI', 'BANK_TRANSFER', 'CASH', 'CHEQUE', 'OTHER', name='paymentmethod'), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('payment_status', sa.Enum('PENDING', 'PARTIALLY_PAID', 'REPORTED_PAID', 'DISPUTED', 'RESOLVED', name='paymentstatus'), nullable=False),
    sa.Column('supporting_evidence', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('agreed_amount >= 0', name='chk_pay_agreed_non_neg'),
    sa.CheckConstraint('amount_due >= 0', name='chk_pay_due_non_neg'),
    sa.CheckConstraint('amount_reported_paid >= 0', name='chk_pay_reported_non_neg'),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendances.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_records_assignment_id'), 'payment_records', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_payment_records_attendance_id'), 'payment_records', ['attendance_id'], unique=False)
    op.create_index(op.f('ix_payment_records_id'), 'payment_records', ['id'], unique=False)
    op.create_index(op.f('ix_payment_records_payment_date'), 'payment_records', ['payment_date'], unique=False)
    op.create_index(op.f('ix_payment_records_payment_status'), 'payment_records', ['payment_status'], unique=False)
    op.create_index(op.f('ix_payment_records_worker_id'), 'payment_records', ['worker_id'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raised_by', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('attendance_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('dispute_type', sa.Enum('ATTENDANCE', 'WAGE', 'PAYMENT', 'WORK_ORDER', 'CANCELLATION', 'IDENTITY', 'SKILL', 'OTHER', name='disputetype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'RESOLVED', 'REJECTED', 'WITHDRAWN', name='disputestatus'), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendances.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payment_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raised_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_assignment_id'), 'disputes', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_disputes_attendance_id'), 'disputes', ['attendance_id'], unique=False)
    op.create_index(op.f('ix_disputes_contractor_id'), 'disputes', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_disputes_dispute_type'), 'disputes', ['dispute_type'], unique=False)
    op.create_index(op.f('ix_disputes_id'), 'disputes', ['id'], unique=False)
    op.create_index(op.f('ix_disputes_payment_id'), 'disputes', ['payment_id'], unique=False)
    op.create_index(op.f('ix_disputes_raised_by'), 'disputes', ['raised_by'], unique=False)
    op.create_index(op.f('ix_disputes_status'), 'disputes', ['status'], unique=False)
    op.create_index(op.f('ix_disputes_worker_id'), 'disputes', ['worker_id'], unique=False)
    op.create_table('dispute_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispute_id', sa.Integer(), nullable=False),
    sa.Column('responder_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('evidence_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responder_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispute_responses_dispute_id'), 'dispute_responses', ['dispute_id'], unique=False)
    op.create_index(op.f('ix_dispute_responses_id'), 'dispute_responses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispute_responses_id'), table_name='dispute_responses')
    op.drop_index(op.f('ix_dispute_responses_dispute_id'), table_name='dispute_responses')
    op.drop_table('dispute_responses')
    op.drop_index(op.f('ix_disputes_worker_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_status'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_raised_by'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_payment_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_dispute_type'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_contractor_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_attendance_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_assignment_id'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_payment_records_worker_id'), table_name='payment_records')
    op.drop_index(op.f('ix_payment_records_payment_status'), table_name='payment_records')
    op.drop_index(op.f('ix_payment_records_payment_date'), table_name='payment_records')
    op.drop_index(op.f('ix_payment_records_id'), table_name='payment_records')
    op.drop_index(op.f('ix_payment_records_attendance_id'), table_name='payment_records')
    op.drop_index(op.f('ix_payment_records_assignment_id'), table_name='payment_records')
    op.drop_table('payment_records')
    op.drop_index(op.f('ix_voice_evidences_worker_id'), table_name='voice_evidences')
    op.drop_index(op.f('ix_voice_evidences_id'), table_name='voice_evidences')
    op.drop_index(op.f('ix_voice_evidences_contractor_id'), table_name='voice_evidences')
    op.drop_index(op.f('ix_voice_evidences_assignment_id'), table_name='voice_evidences')
    op.drop_table('voice_evidences')
    op.drop_index(op.f('ix_sos_alerts_worker_id'), table_name='sos_alerts')
    op.drop_index(op.f('ix_sos_alerts_status'), table_name='sos_alerts')
    op.drop_index(op.f('ix_sos_alerts_site_id'), table_name='sos_alerts')
    op.drop_index(op.f('ix_sos_alerts_project_id'), table_name='sos_alerts')
    op.drop_index(op.f('ix_sos_alerts_id'), table_name='sos_alerts')
    op.drop_index(op.f('ix_sos_alerts_assignment_id'), table_name='sos_alerts')
    op.drop_table('sos_alerts')
    op.drop_index(op.f('ix_incidents_worker_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_site_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_project_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_incident_type'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_contractor_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_assignment_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_attendances_worker_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_date'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_attendance_status'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_assignment_id'), table_name='attendances')
    op.drop_table('attendances')
    op.drop_index(op.f('ix_worker_contact_releases_worker_id'), table_name='worker_contact_releases')
    op.drop_index(op.f('ix_worker_contact_releases_offer_id'), table_name='worker_contact_releases')
    op.drop_index(op.f('ix_worker_contact_releases_id'), table_name='worker_contact_releases')
    op.drop_index(op.f('ix_worker_contact_releases_contractor_id'), table_name='worker_contact_releases')
    op.drop_table('worker_contact_releases')
    op.drop_index(op.f('ix_work_order_versions_work_order_id'), table_name='work_order_versions')
    op.drop_index(op.f('ix_work_order_versions_id'), table_name='work_order_versions')
    op.drop_table('work_order_versions')
    op.drop_index(op.f('ix_communication_logs_worker_id'), table_name='communication_logs')
    op.drop_index(op.f('ix_communication_logs_status'), table_name='communication_logs')
    op.drop_index(op.f('ix_communication_logs_offer_id'), table_name='communication_logs')
    op.drop_index(op.f('ix_communication_logs_id'), table_name='communication_logs')
    op.drop_index(op.f('ix_communication_logs_created_at'), table_name='communication_logs')
    op.drop_index(op.f('ix_communication_logs_contractor_id'), table_name='communication_logs')
    op.drop_table('communication_logs')
    op.drop_index(op.f('ix_assignments_worker_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_work_order_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_status'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_site_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_project_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_work_orders_worker_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_status'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_site_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_requirement_item_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_project_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_contractor_id'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_job_offers_worker_id'), table_name='job_offers')
    op.drop_index(op.f('ix_job_offers_status'), table_name='job_offers')
    op.drop_index(op.f('ix_job_offers_requirement_item_id'), table_name='job_offers')
    op.drop_index(op.f('ix_job_offers_id'), table_name='job_offers')
    op.drop_table('job_offers')
    op.drop_index(op.f('ix_labour_requirement_items_trade_id'), table_name='labour_requirement_items')
    op.drop_index(op.f('ix_labour_requirement_items_skill_id'), table_name='labour_requirement_items')
    op.drop_index(op.f('ix_labour_requirement_items_requirement_id'), table_name='labour_requirement_items')
    op.drop_index(op.f('ix_labour_requirement_items_id'), table_name='labour_requirement_items')
    op.drop_table('labour_requirement_items')
    op.drop_index(op.f('ix_labour_requirements_status'), table_name='labour_requirements')
    op.drop_index(op.f('ix_labour_requirements_site_id'), table_name='labour_requirements')
    op.drop_index(op.f('ix_labour_requirements_project_id'), table_name='labour_requirements')
    op.drop_index(op.f('ix_labour_requirements_id'), table_name='labour_requirements')
    op.drop_index(op.f('ix_labour_requirements_contractor_id'), table_name='labour_requirements')
    op.drop_table('labour_requirements')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_sites_supervisor_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_region'), table_name='sites')
    op.drop_index(op.f('ix_sites_project_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_worker_skills_worker_id'), table_name='worker_skills')
    op.drop_index(op.f('ix_worker_skills_skill_id'), table_name='worker_skills')
    op.drop_index(op.f('ix_worker_skills_id'), table_name='worker_skills')
    op.drop_table('worker_skills')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_contractor_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_projects_project_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_contractor_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_preferred_workers_worker_id'), table_name='preferred_workers')
    op.drop_index(op.f('ix_preferred_workers_id'), table_name='preferred_workers')
    op.drop_index(op.f('ix_preferred_workers_contractor_id'), table_name='preferred_workers')
    op.drop_table('preferred_workers')
    op.drop_index(op.f('ix_workers_user_id'), table_name='workers')
    op.drop_index(op.f('ix_workers_id'), table_name='workers')
    op.drop_index(op.f('ix_workers_availability_status'), table_name='workers')
    op.drop_table('workers')
    op.drop_index(op.f('ix_skills_trade_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_contractors_user_id'), table_name='contractors')
    op.drop_index(op.f('ix_contractors_id'), table_name='contractors')
    op.drop_table('contractors')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trades_name'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_table('trades')
    # ### end Alembic commands ###
